### ISSUE TITLE
How can we have Single Database with table prefix for every tenant.

### ISSUE THREAD

**Issue by xyrintech** [orchestral/tenanti#46] opened 2017-07-07 12:34 UTC

**Comment by xyrintech** [comment] 2017-07-07 12:34
Please refer https://stackoverflow.com/questions/44970393/single-domain-with-single-database-with-orchestral-tenanti

**Comment by crynobone** [comment] 2017-07-25 14:45
Closing as this is not a bug.

**Closed by crynobone** 2017-07-25 14:45 UTC
